text1 = "It was about (Number) (Measure of time) ago when I arrived at the hospital in a (Mode of Transportation). The hospital is a/an (Adjective) place, there are a lot of (Adjective2) (Noun) here. There are nurses here who have (Color) (Part of the Body ). If someone wants to come into my room I told them that they have to (Verb) first. Ive decorated my room with (Number2) (Noun2). Today I talked to a doctor and they were wearing a (Noun3) on their ( Part of the Body 2). I heard that all doctors (Verb) (Noun4) every day for breakfast. The most ( Adjective3) thing about being in the hospital is the (Silly Word) (Noun) !"
text2 = "This weekend I am going camping with ( Proper Noun (Persons Name)). I packed my lantern, sleeping bag, and (Noun). I am so (Adjective (Feeling)) to (Verb) in a tent. I am (Adjective (Feeling) 2) we might see a(n) (Animal), I hear theyre kind of dangerous. While were camping, we are going to hike, fish, and (Verb2). I have heard that the (Color) lake is great for ( Verb (ending in ing) ). Then we will (Adverb (ending in ly)) hike through the forest for (Number) (Measure of Time). If I see a (Color) (Animal) while hiking, I am going to bring it home as a pet! At night we will tell (Number) (Silly Word) stories and roast (Noun2) around the campfire!!"
text3 = "Dear (Proper Noun (Persons Name) ), I am writing to you from a (Adjective) castle in an enchanted forest. I found myself here one day after going for a ride on a (Color) (Animal) in (Place). There are (Adjective2) (Magical Creature (Plural)) and (Adjective3) (Magical Creature (Plural)2) here! In the ( Room in a House) there is a pool full of (Noun). I fall asleep each night on a (Noun2) of (Noun(Plural)3) and dream of (Adjective4) ( Noun (Plural)4). It feels as though I have lived here for (Number) ( Measure of time). I hope one day you can visit, although the only way to get here now is (Verb (ending in ing)) on a (Adjective5) (Noun5)!!"
temp = input("Please, pick one of the templates: 1, 2 or 3")
if temp == '1':
  number = input('Number')
  measure_of_time = input('measure of time')
  mode_of_transportation = input('mode of transporation')
  adjective = input('adjective')
  adjective2 = input('other adjective')
  noun = input('noun')
  color = input('color')
  part_of_the_body = input('part of the body')
  verb = input('verb')
  number2 = input('another num')
  noun2 = input('another noun')
  noun3 = input('another noun')
  part_of_the_body2 = input('another part of the body')
  noun4 = input('another noun')
  adjective3 = input('another adjective')
  silly_word = input('silly word')
  text1 = text1.replace('(Number)', number).replace('(Measure of time)', measure_of_time).replace('(Mode of Transportation)', mode_of_transportation).replace('(Adjective)', adjective).replace('(Adjective2)', adjective2).replace('(Noun)', noun).replace('(Color)', color).replace('(Part of the Body )', part_of_the_body).replace('(Verb)', verb).replace('(Number2)', number2).replace('(Noun2)', noun2).replace('(Noun3)', noun3).replace('( Part of the Body 2)', part_of_the_body2).replace('(Noun4)',noun4).replace('( Adjective3)', adjective3).replace('(Silly Word)', silly_word)
  print(text1)
elif temp == '2':
  proper_noun = input("persons name")
  noun = input('type a noun')
  adjective = input('adjective')
  verb = input('verb')
  adjective2 = input('other adjective')
  animal = input('an animal')
  verb2 = input('another verb')
  color = input('color')
  verb3 = input('verb + ing')
  adverb = input('adverb + ly')
  number = input('number')
  measure_of_time = input('measure of time')
  silly_word = input('silly word')
  noun2 = input('another noun')
  text2 = text2.replace('( Proper Noun (Persons Name))', proper_noun).replace('(Noun)', noun).replace('(Adjective (Feeling))', adjective).replace('(Verb)', verb).replace('(Adjective (Feeling) 2)', adjective2).replace('(Animal)', animal).replace('(Verb2)', verb2).replace('(Color)', color).replace('( Verb (ending in ing) )', verb3).replace('(Adverb (ending in ly))', adverb).replace('(Number)', number).replace('(Measure of Time)', measure_of_time).replace('(Silly Word)', silly_word).replace('(Noun2)', noun2)
  print(text2)
elif temp == '3':
  proper_noun = input("person's name")
  adjective = input('adjective')
  color = input('color')
  animal = input('animal')
  place = input('place')
  adjective2 = input('another adjective')
  magical_creature = input('magical creature')
  adjective3 = input('other adjective')
  magical_creature2 = input('another magical creature')
  room_in_a_house = input('room in a house')
  noun = input('noun')
  noun2 = input('one more noun')
  noun3 = input('other noun')
  adjective4 = input('other adjective')
  noun4 = input('another noun')
  number = input('number')
  verb = input('verb')
  measure_of_time = input('measure of time')
  verb2 = input('verb + ing')
  adjective5 = input('another adjective')
  noun5 = input('another noun')
  text3 = text3.replace('(Proper Noun (Persons Name) )', proper_noun).replace('(Adjective)', adjective).replace('(Color)', color).replace('(Animal)', animal).replace('(Place)', place).replace('(Adjective2)', adjective2).replace('(Magical Creature (Plural))', magical_creature).replace('(Adjective3)', adjective3).replace('(Magical Creature (Plural)2)', magical_creature2).replace('( Room in a House)', room_in_a_house).replace('(Noun)', noun).replace('(Noun2)', noun2).replace('(Noun(Plural)3)', noun3).replace('(Adjective4)', adjective4).replace('( Noun (Plural)4)', noun4).replace('(Number)', number).replace('( Measure of time)', measure_of_time).replace('(Verb (ending in ing))', verb2).replace('(Adjective5)', adjective5).replace('(Noun5)', noun5)
  print(text3)
else:
  print('please choose correct template')
